In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('../data/processed/HR_Dataset_Clean.csv')
date_cols = ['StartDate', 'ExitDate', 'DOB', 'Survey Date', 'Training Date']
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

df['Attrition'] = df['Attrition'].astype(bool)
df.shape

(3000, 36)

In [3]:
df['PayZone'].value_counts()

PayZone
Zone A    1062
Zone B     985
Zone C     953
Name: count, dtype: int64

In [4]:
pd.crosstab(df['PayZone'], df['GenderCode'], normalize='index') * 100

GenderCode     Female       Male
PayZone
Zone A      56.308851  43.691149
Zone B      56.345178  43.654822
Zone C      55.508919  44.491081

In [5]:
pd.crosstab(df['PayZone'], df['RaceDesc'], normalize='index') * 100

RaceDesc      Asian      Black   Hispanic      Other      White
PayZone
Zone A    20.056497  23.352166  17.514124  19.303202  19.774011
Zone B    21.827411  18.071066  20.609137  19.289340  20.203046
Zone C    21.091291  20.146905  19.202518  19.622246  19.937041

In [6]:
df.groupby('GenderCode')['Current Employee Rating'].mean()

GenderCode
Female    2.985137
Male      2.948407
Name: Current Employee Rating, dtype: float64